name: OpenGrep Triage and Remediation Grouped Prod

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

env:
  OPENGREP_VERSION: "v1.16.1"

jobs:
  opengrep-scan-and-process:
    runs-on: ubuntu-latest
    env:
      PROCESSING_MODE: group_cc
      GROUPING_STRATEGY: smart
      AUTO_CREATE_PRS: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: opengrep-sarif
          path: vuln_file/output_sarif_100.sarif
          retention-days: 7

      - name: AppSecAI Triage and Remediation
        uses: AppSecureAI/automation-action@v1
        with:
          file: vuln_file/output_sarif_100.sarif
